name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Install dependencies
      run: go mod download
    - name: Build project
      run: make wasm

  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev xvfb
    - name: Run tests
      run: |
        rm -f ~/.Xauthority
        touch ~/.Xauthority
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        xauth generate :99 . trusted
        make test
